/*
 **************************** DO NOT EDIT THIS FILE ****************************
 ************ ANY CHANGES MADE WILL BE DISCARDED BEFORE EVALUATION *************
 */

#include <iostream>
#include "vertex.hpp"

/*********************************************************/

/**
 * vertex constructor to create a new vertex
 * @param id integer label of the vertex
 */
vertex::vertex(int id) {
	this->id = id;
}
	
/**
 * get the integer label of a vertex
 * @return integer label of the vertex
 */
int vertex::getId() {
	return id;
}

/**
 * print the integer label of a vertex
 */
void vertex::print() {
	cout << id << " ";
}

/*********************************************************/

/**
 * vertexNode constructor to create a new vertex node
 * @param v the vertex object
 */
vertexNode::vertexNode(vertex* v) {
	this->v = v;
	next = NULL;
}

/**
 * get the vertex object from a vertexNode
 * @return the vertex object in the node
 */
vertex* vertexNode::getVertex() {
	return this->v;
}

/**
 * get the next value of a vertexNode
 * @return the next value of the vertexNode
 */
vertexNode* vertexNode::getNext() {
	return this->next;
}

/**
 * set the next value of a vertexNode
 * @param node the next node
 */
void vertexNode::setNext(vertexNode* node) {
	this->next = node;
}


/**
 * print a vertex node
 */
void vertexNode::print() {
	v->print();
}

/*********************************************************/

/**
 * vertexList constructor to create an empty vertex list
 */
vertexList::vertexList() {
	head = NULL;
	size = 0;
}

/**
 * get the head of a vertexList
 * @return the head of the vertexList
 */
vertexNode* vertexList::getHead() {
	return this->head;
}

/**
 * get the size of a vertexList
 * @return the size of the vertexList
 */
int vertexList::getSize() {
	return size;
}

/**
 * add a new vertex node to a vertex list (at front)
 * @param node the vertex node to be added
 */
void vertexList::addNode(vertexNode* node) {
	node->setNext(head);
	head = node;
	size++;
}

/**
 * print a vertex list
 */
void vertexList::print() {
	vertexNode* temp = head;
	while(temp != NULL) {
		temp->print();
		temp = temp->getNext();
		cout << "-> ";
	}
	cout << "NULL" << endl;
}

/*********************************************************/
